### ISSUE TITLE
Long number with many "9"s parsed to wrong result

### ISSUE THREAD

**Issue by dnechay** [grantila/awesome-phonenumber#122]
Hey 👋🏼

We found out that in some special cases phone number input isn't being parsed properly.
Example input:  `+3399999999999999999`
What we have as output:
```
{
  number: {
    input: '+3399999999999999999',
    international: '+33 100000000000000000',
    national: '100000000000000000',
    e164: '+33100000000000000000',
    rfc3966: 'tel:+33-100000000000000000',
    significant: '100000000000000000'
  },
  regionCode: 'FR',
  valid: false,
  possible: false,
  canBeInternationallyDialled: true,
  possibility: 'too-long',
  type: 'unknown',
  typeIsMobile: false,
  typeIsFixedLine: false,
  countryCode: 33
}
```
Same behavior is for js-version of libphonenumber ([by this link](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)).
At the same time the original version of library works as expected: https://libphonenumber.appspot.com/phonenumberparser?number=%2B3399999999999999999

The number itself is not valid, so shouldn't be critical for many users, so just sharing in case it might be useful

**Comment by grantila** [comment]
Certainly looks weird, you're right. Not sure why, but as it happens in the js version of the lib, it might be that it converts to a number that overflows. Nothing really to do about it, I guess the appspot instance runs the Java version without this issue.

Closing as there's nothing that can be done, and because the `valid` property must be checked before trusting any other field.
