### ISSUE TITLE
Dynamically load locale?

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [grantila/awesome-phonenumber#16]
Even with all the minification, this library is pretty large. It would be cool if there was a way to dynamically load only the stuff needed for a particular locale.

Like for instance, an AsYouTypeFormatter for only english.

**Comment by grantila** [comment]
This is most probably impossible due to upstream [libphonenumber](https://github.com/googlei18n/libphonenumber) being a huge monolith. I'm afraid this is not gonna happen, unless upstream has a way to deal with it, and as much as I would encourage you to create an issue in libphonenumber, I'll have to warn you too. It won't happen..
