### ISSUE TITLE
Update to libphonenumber 8.9.5

### ISSUE THREAD

**Issue by fallemand** [grantila/awesome-phonenumber#25]
Hello Gustaf, is it possible to update `libphonenumber` to `8.9.5`?
We need some validation fixes.
Thanks for your time.

**Comment by fallemand** [comment]
Please, can you tell me when you can take this issue? or if you have a guide, I can make a pull request.
Thanks.

**Comment by grantila** [comment]
I tried to bump it, but my current scripts downloads the latest closure library, which obviously fails at compiling my code (exporting to global/window/self), and since closure is a complete nightmare to use (horrible/missing documentation), after hours and hours I gave up. Will have a look again, maybe using a pinned (old) version of closure.

**Comment by grantila** [comment]
8.9.7 now with old closure

**Comment by fallemand** [comment]
Thanks for your effort!
