### ISSUE TITLE
Question: protobuf?

### ISSUE THREAD

**Issue by chris-findlay** [grantila/awesome-phonenumber#37]
I note that the output appears to include the Protobuf part of the closure runtime lib (or at least it's header comment).  Do you know if this tree-shakes out?

**Comment by grantila** [comment]
By looking at the compiled code, I can't see any remnants of protobuf per se, and it's a bit sad the copyright comment is there, since it's actually not used in the code itself (but probably some other part of the upstream libphonenumber).

Tree-shaking is entirely implementation dependent, and I suppose you refer to webpack? Afaik, it only shakes *ES6 modules* by ignoring exported features that aren't ever imported. In this case, it's pure CommonJS code, so I'd suppose everything will be there.

What you **can** do, is to uglify-eliminate comments. But these comments likely compress well in an assembled bundle.

**Comment by chris-findlay** [comment]
Thanx (c:
