### ISSUE TITLE
'input' not in getNumber() formats

### ISSUE THREAD

**Issue by axrae** [grantila/awesome-phonenumber#41]
I'm curious about the reasoning behind the omission of 'input' from the enum of allowed formats for getNumber()? The parameter does work as expected, but of course TSLint throws a fit over it.

[https://www.npmjs.com/package/awesome-phonenumber#phone-number-formats](https://www.npmjs.com/package/awesome-phonenumber#phone-number-formats)

**Comment by grantila** [comment]
The 'input' _happens_ to work because you're reading from an internal data structure which *today* has a field called 'input.
The enum comes from [libphonenumber](https://javadoc.io/static/com.googlecode.libphonenumber/libphonenumber/8.10.22/com/google/i18n/phonenumbers/PhoneNumberUtil.PhoneNumberFormat.html) with the addition of [getNational**Significant**Number​](https://javadoc.io/static/com.googlecode.libphonenumber/libphonenumber/8.10.22/com/google/i18n/phonenumbers/PhoneNumberUtil.html#getNationalSignificantNumber-com.google.i18n.phonenumbers.Phonenumber.PhoneNumber-) which for some reason is handled differently in libphonenumber.

If you use 'input' for the value passed into awesome-phonenumber, I'd recommend you store that separately instead to be sure your code still works if I change this implementation in the future.

**Comment by grantila** [comment]
consider 'input' for 3.0
