### ISSUE TITLE
ayt.getPhoneNumber().getNumber() can return undefined while the typing says it will always return a string

### ISSUE THREAD

**Issue by acoutts** [grantila/awesome-phonenumber#44]
I think the typing in `lib/index.d.ts` should be updated to reflect that this method can return undefined. Currently it is typed saying it will always return a string but the following code will return undefined if there are not at least 2 digits in the phone number:

```javascript
const PhoneNumber = require("awesome-phonenumber")

const ayt = PhoneNumber.getAsYouType("US")
console.log(ayt.getPhoneNumber().getNumber()) // undefined

ayt.addChar("1") // "1"
ayt.addChar("1") // "11"
console.log(ayt.getPhoneNumber().getNumber()) // "11"
```

**Comment by grantila** [comment]
Your concern is valid, but I can't change this without braking major version. Not just for pedantic reasons, but because _a lot_ of code would fail since you would always have to check the return type. I've been thinking of breaking the API completely for 3.0 and remove classes and only have free functions. That makes composition easier.

I'm actually surprised you get a number at all, this comes from upstream libphonenumber...

What you **should** do, is check the `getPhoneNumber().isValid()` and only when it's true, do a `.getNumber()`. That's not something you can describe in TS since we don't have complex _contracts_ in the language, so you'll have to take my word for it..

**Comment by acoutts** [comment]
Thanks for explaining. A dirty workaround for now to make sure I at least always get a string is to simply call it like this:
```javascript
const value = ayt.getPhoneNumber().getNumber() || "" // empty string instead of undefined
```
