### ISSUE TITLE
Uncaught TypeError: Cannot read property 'WeakMap' of undefined

### ISSUE THREAD

**Issue by bravadomizzou** [grantila/awesome-phonenumber#62]
The most recent version introduces an error in applications:

"Uncaught TypeError: Cannot read property 'WeakMap' of undefined".

**Comment by grantila** [comment]
Hmm, I wonder what system this is on 🤔
WeakMap's been there [since Node 0.12](https://node.green/#ES2015-built-ins-WeakMap-basic-functionality) and in browsers since [around 2013](https://caniuse.com/mdn-javascript_builtins_weakmap).. On the other hand, this happened since I added a `Set` usage, likely closure compiler doing something funky.

And that "of undefined" is suspicious...

Fixing by removing Set..
