### ISSUE TITLE
getRegionCode and getCountryCode returning wrong values if number starts with double zeros

### ISSUE THREAD

**Issue by Therealskythe** [grantila/awesome-phonenumber#78]
The module does not recognize non-e164 numbers and returns incorrect region and country code (formatting and validation seem to work).

For example:
```
var pn = new PhoneNumber("0049040398272", "ES");
console.log(pn.getNumber("e164"));
console.log(pn.getRegionCode("e164")); // Should return DE, but does not
console.log(pn.getCountryCode("e164")); // Should return 49, but does not
```

The above will return Spain as the country (because it's the default, I guess) instead of Germany. If you replace the two leading zeros with a plus sign though, the correct country is returned.

I would expect the tool to recognize both 0049 and +49. Am I missing something?

(On a little side note: unlike with libphonenumber-js, I could not find any info on what the default language is actually for and leaving it out seems to produce even worse results. Maybe you could add some explanation to the README?)

**Comment by grantila** [comment]
Either use the international standard `e164` as only argument, i.e. prefixed with `+`.
Or use the _national_ phone number format as first argument, and region code (e.g. 'ES') as second.

**Comment by Therealskythe** [comment]
> Either use the international standard `e164` as only argument, i.e. prefixed with `+`. Or use the _national_ phone number format as first argument, and region code (e.g. 'ES') as second.

Isn't the point of this library the validation, parsing and formatting of phone numbers that might or might not be valid and / or in e164 format?

Is it possible to feed unknown phone numbers into it and have them parsed and validated?

**Comment by grantila** [comment]
No, the library isn't supposed to understand invalid phone numbers and guess what was meant. A phone number starting with 00 is invalid (at least a Spanish one).

This is basically a pre-compiled wrapper on top of google's libphonenumber without any magic logic on top of it, just a nicer/simpler API.

**Comment by Therealskythe** [comment]
So you're saying lines 3 and 4 in the above example are not bugs, but expected behaviour?

I hope people realize how this works then and don't use this for validation and parsing in production environments. Google's libphonenumber does _not_ do this btw.

**Comment by grantila** [comment]
You're right in that lines 3 and 4 doesn't make sense, and they should (whatever they return). At least they should correspond to the e164 number. I'll look into this.

But, for reference, 00 is not a universal standard for describing international phone numbers, + is. And you specified 'ES'. Double zeroes are common when _dialing_ though, perhaps that's why libphonenumber accepts it.

**Comment by grantila** [comment]
Google explicitly documents the problem with German (49) numbers here: https://github.com/google/libphonenumber/blob/master/FAQ.md#why-wasnt-the-country-code-removed-when-parsing

And explains why 00 isn't the same as + here: https://github.com/google/libphonenumber/blob/master/FAQ.md#why-wasnt-00-parsed-the-same-as-

Your input vs expectations _are_ invalid. You specify Spanish region code with a number starting with `0049`, expecting it to somehow believe this to be a German number because the country code of Germany is 49. The valid input for your expected output should begin with `+49`, not `0049`.

The `parse` function in libphonenumber fails to parse the number `0049040398272` as-is (but handles `+49040398272` of course), but it succeeds if hinting (the incorrect) Spanish region code, because it _knows_ that Spain doesn't have a national prefix 00.

If you'd specified e.g. 'US' as region code instead of 'ES', libphonenumber wouldn't understand how to parse this, so again, the input is invalid, or at least bad.

This is an extreme edge case in libphonenumber, probably the reason no one has reported this until now, I'm sorry for not understanding this before, it was _certainly not clear at all_.
